apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: java-test
    spec:
      containers:
      - name: gke-test
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        resources:
          requests:
            cpu: "100m"

apiVersion: v1
kind: Service
metadata:
  name: java-test-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: java-test

